baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "SJ Portfolio"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  # main:
  #   - identifier: blog
  #     name: Blog
  #     title: Blog posts
  #     url: /blogs
  #     weight: 1
  #   - identifier: gallery
  #     name: Gallery
  #     title: Blog posts
  #     url: /gallery
  #     weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "SJ Portfolio"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/cool.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "SJ's Lab" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Shaunak"
    subtitle: "and I love building software"
    content: "A passionate software developer, bookworm and a musician. I believe in transforming code into solutions, one algorithm at a time."
    image: /images/hero.jpeg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "Shaunak_Juvekar_Resume.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/shaunakjuvekar
        - icon: fab fa-goodreads
          url: https://www.goodreads.com/review/list/26060784?ref=nav_mybooks
      customIcons:
        - icon: /images/yt2.png
          url: "https://www.youtube.com/channel/UC_uSBDBjekX-ECgBnLfyjxg"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.jpeg"
    content: |-
      Hey there! I'm a software engineer with a passion for web development. I am currently a graduate student at Virginia Tech, pursuing a master's degree in Computer Science in Blacksburg, Virginia. I’m well versed in areas such as Software Engineering, Data Analytics, Database Systems, Big Data and User Interfaces. My core technical skillset is Python, JavaScript, Pandas, Numpy, ReactJS, SQL, HTML/CSS, Elasticsearch, Docker and Apache Spark. Apart from this, I also love project management - managing teams and projects, coordinating team efforts and ensuring reliable and quality delivery. 

      During my leisure hours, I find joy in a variety of activities, including playing the piano, reading books, experimenting in the kitchen, and venturing on hikes. While I dedicated numerous years to western classical music, my current inclination is towards spontaneous piano improvisation. In the realm of literature, I am an avid reader across all genres with a particular love for fantasy fiction. I possess a natural curiosity for seeking out novel experiences and innovative avenues for personal and professional growth.
    skills:
      enable: false
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "React"
        - "Node"
        - "Express"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Software Developer Intern"
        company: "Mediaocean"
        companyUrl: "https://www.mediaocean.com/"
        date: "June 2023 - Aug 2023"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        info:
          enable: false
        content: |-
          Spearheaded the implementation of a thumbnail generation service using AWS Lambda, AWS S3, Python, FFMPEG, GraphQL, and ReactJS.

      - job: "Software Developer"
        company: "Gibots"
        companyUrl: "https://gibots.com"
        date: "July 2020 - July 2021"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: false
          content: I worked as a software developer for more than one year in Amazon.
        content: |-
          Implemented end to end RPA solutions by developing APIs using ExpressJS and integrated Java (Apache PDFBox), Javascript (Officegen) and Python (PdfPlumber) libraries, generating up to 90% savings in manpower cost.
          

      - job: "Software Engineer"
        company: "Vodafone"
        companyUrl: "https://www.vodafone.com/careers/professional-career-areas/shared-services"
        date: "July 2018 - March 2020"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |-
          Engineered automation solutions for Vodafone TV for their STB, Web and Android platforms using Python and Lua.

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Master of Engineering in Computer Science"
        school:
          name: "Virginia Tech"
          url: "https://www.vt.edu/"
        date: "2022 - 2024"
        GPA: "3.9 out of 4.0"
        content: |-
          Courses: Information Storage and Retrieval, Big Data Engineering, Data Analytics, Networks Programming, Software Engineering, Web Development, Software Project Management

      - title: "Bachelor of Engineering in Electronics and Telecommunication"
        school:
          name: "MIT - Pune University"
          url: "https://mitwpu.edu.in/"
        date: "2014 - 2018"
        GPA: "3.91 out of 4.0"
        content: |-
          Relevant courses: Data Structures and Algorithms, Object Oriented Programming, Computer Networks, AI
        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"
      

  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
     
      - title: Vodafone Rising Star Award
        content: Won the award for innovative technical solutions for the Vodafone TV product.
        image: /images/voda.jpeg
      - title: Cool Guru Award
        content: Won the award at Gibots for consecutive high pressure software deliveries.
        image: /images/gibots.jpeg
      - title: The Ultimate MySQL Bootcamp
        content: Completed the most comprehensive course on SQL
        url: https://example.com
        image: /images/udemy.jpeg

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: SWEEP
        content: SWEEP (Solid Waste Echelon-Embedded Planner) is a web-based tool for designing a Municipal Solid Waste (MSW) management system
        image: /images/projects/Routes.png
        featured:
          name: Demo
          link: "https://sweep.discovery.cs.vt.edu/"
        badges:
          - "ReactJS"
          - "LeafletJS"
          - "Python Flask"
        links:
          - icon: fab fa-github
            url: https://github.com/shaunakjuvekar/SWM
        

      - title: LetsGo - Your Online Travel Coordinator 
        content: A social network-like web app for VT students to coordinate group travel arrangements
        image: /images/projects/letsgo.png
    
        badges:
          - "ReactJS"
          - "NodeJS"
          - "MySQL"
        links:
          - icon: fab fa-github
            url: https://github.com/shaunakjuvekar/letsgo

      - title: Anomaly Detection System
        content: A Big Data and Machine Learning based system which detects anomalies in SSH logs
        image: /images/projects/anomaly.avif
     
        badges:
          - "Apache Spark"
          - "Machine Learning"
          - "Python"
        links:
          - icon: fab fa-github
            url: https://github.com/shaunakjuvekar/anomaly_detection

      - title: Search Engine for ETD Data
        content: A search engine using Elasticsearch and Python for 30K ETD documents - Electronic theses and dissertations
        image: /images/projects/search.avif
       
        badges:
          - "Elasticsearch"
          - "Logging"
          - "Python"
        links:
          - icon: fab fa-github
            url: https://github.com/shaunakjuvekar/etd_search

      - title: Packet Delivery System
        content: A Python application which enables transmission of network packets reliably in a Docker setup
        image: /images/projects/packets1.avif
        
        badges:
          - "Python"
          - "Computer Networks"
        links:
          - icon: fab fa-github
            url: https://github.com/shaunakjuvekar/Packet-Delivery-System

     

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: I'm currently looking for new opportunities in Software Development and Data Science. My inbox is always open, whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: shaunak.juvekar@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/shaunakjuvekar
      linkedin: https://www.linkedin.com/in/shaunak-juvekar/
      # youtube: https://www.youtube.com/channel/UC_uSBDBjekX-ECgBnLfyjxg
      # goodreads: https://www.goodreads.com/review/list/26060784?ref=nav_mybooks
      

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
